# Data paths
data:
  raw_data:
    instant_data:
      file: /app/data/raw/instant_data.csv
    historical_data:
      file: /app/data/raw/historical_data.csv
  predictions:
    instant_data:
      predictions_file: /app/data/predictions/instant_predictions.csv
      metrics_file: /app/data/predictions/instant_metrics.csv
    history_data:
      predictions_file: "/app/data/predictions/history_data/history_predictions.csv"
      metrics_file: "/app/data/predictions/history_data/history_metrics.csv"

# Kafka configuration
kafka:
  bootstrap_servers: kafka:29092
  security_protocol: PLAINTEXT
  topic: bitcoin-prices
  consumer_group: "bitcoin-dashboard"

# Model configuration
model:
  instant:
    evaluation_window: 300  # 5 minutes in seconds
    forecast_horizon: 1     # 1 second ahead
    learning_rate: 0.01    # Learning rate for model training
    vi_steps: 500         # Number of variational inference steps (reduced from 1000)
    num_samples: 100      # Number of samples for forecasting (reduced from 1000)
    feature_windows:       # Feature windows configuration
      log_return: 5        # 5-minute window for log returns
      vol_rolling: [15, 30, 60]  # List of windows for volatility rolling window
      ma_short: 30         # 30-minute window for short-term moving average
      ma_long: 120         # 2-hour window for long-term moving average
    resample_freq: "5T"    # 5-minute intervals
    lookback: 120          # Lookback period for features
    window_size: 300       # 5 minutes in seconds
  history:
    evaluation_window: 168 # hours (1 week)
    forecast_horizon: 24   # steps
    learning_rate: 0.01    # Learning rate for model training
    vi_steps: 1000         # Number of variational inference steps
    num_samples: 1000      # Number of samples for forecasting
    num_seasons: 7         # Number of seasons for seasonal model
    rolling_vol: 7         # Days for rolling volatility calculation
    seasonal_period: 24    # Hours in a seasonal period

# Dashboard configuration
dashboard:
  refresh_interval: 5      # seconds
  default_time_range_days: 1  # reduced from 7
  chart_height: 600
  theme: "plotly_white"
  data_aggregation: "1H"   # Aggregate data to hourly intervals 