apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-data-pvc
  namespace: bitcoin-prediction
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-pvc
  namespace: bitcoin-prediction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data-pvc
  namespace: bitcoin-prediction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-log-pvc
  namespace: bitcoin-prediction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 